### PR TITLE
Targets

### PR DESCRIPTION
**Pull request by jlouis**
Slowly moving towards dialyzer specs...

### CODE REVIEW

**Comment by yrashk** [comment]
Funny, I just was adding skip_deps myself...

But speaking about debug_info, how about something like this

```
dialyze:
            @./rebar clean
            @./rebar compile debug_info=1
            @./rebar dialyze skip_deps=true
            @./rebar clean
```

?

**Comment by jlouis** [comment]
Fine by me to add that. The dialyzer doesn't like typespecs.hrl though for some reason (which I am more inclined to call a problem inside the dialyzer)

**Comment by yrashk** [comment]
Well, I don't see a reason why it shouldn't like it. What do you get?

P.S. I will merge this soon

**Comment by jlouis** [comment]
Something along the lines of the fact that if have a type

```
 -type foo :: ...
```

and also

```
 -type foo(A) :: ... use of A ...
```

then it errs (with a quite nasty error that forgets to print out the string correctly) that the type in question is already defined. I am quite sure it is an internal dialyzer error.

**Comment by yrashk** [comment]
Oh, I think I have the same problem, it looks like a internal problem to me, too. Shouldn't we report it to erlang-bugs or something?

**Comment by jlouis** [comment]
Start by asking on erlang-questions@ with a minimal example.

**Comment by yrashk** [comment]
Yeah, I guess this is the only way.

**Pull request merged**
